### ISSUE TITLE
Connect problems using github example code on an esp32-s2 feather

### ISSUE THREAD

**Issue by blackMagic001** [adafruit/Adafruit_CircuitPython_MiniMQTT#111]
Hi @brentru @kattni ,

I have been unable to connect to io.adafruit by mqtt, and I wonder if it is the minimqtt library.   I am using the example code below with zero changes.

**Code:**[ /examples/minimqtt_simpletest.py](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/main/examples/minimqtt_simpletest.py)

Board: Adafruit Esp32-S2 Feather

Firmware: CircuitPython 7.3.2

secrets = {
    'ssid'                 : '[deleted]',
    'password'        : '[deleted]',
    'aio_username' : '[deleted]',
    'aio_key'           : '[deleted]',
    'timezone'        : "America/New_York", # http://worldtimeapi.org/timezones
    'broker'             : 'io.adafruit.com',
    'port'                : 1883
    }

**Output:**
Connecting to [home network]
Connected to [home network]!
Attempting to connect to io.adafruit.com
Traceback (most recent call last):
  File "code.py", line 97, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 441, in connect
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 254, in _get_connect_socket
TypeError: extra positional arguments given

I was having similar errors using the Unexpected Maker ESP32-S2 as well.

**Possibly related issues?** 
[#3836](https://github.com/adafruit/circuitpython/issues/3836)
[#4394](https://github.com/adafruit/circuitpython/issues/4394)
I should note that the issues on these links may be specific to the Unexpected Maker board.  I may post a separate issue on this later.

**Comment by vladak** [comment]
This was reported in 2022 against unknown MiniMQTT version. Chances are that some old MiniMQTT version was used that did not have the changes for PR #94.
