### ISSUE TITLE
allow to set retry count for connect()

### ISSUE THREAD

**Issue by vladak** [adafruit/Adafruit_CircuitPython_MiniMQTT#114]
Similar to #112, it would be nice to be able to set the retry count for `connect()`. Currently it is hard coded to 5: https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/67e0adeea9342787fbe715bd1776a8df983ad66b/adafruit_minimqtt/adafruit_minimqtt.py#L254-L255

**Comment by tekktrik** [comment]
You could submit a PR with a similar fix as before, if you're up for it!
