### ISSUE TITLE
maybe less "mini" in the future?

### ISSUE THREAD

**Issue by schaefer01** [adafruit/Adafruit_CircuitPython_MiniMQTT#134]
hi,

  my first attempt to use minimqtt to talk to a server on a wired lan returned the error:
     AssertionError: Error: SSL/TLS is not currently supported by CircuitPython.
    1. is this a circuitpython problem or a minimqtt problem
    2. in either case, will SSL/TLS be supported in the future?
    
bob s.

**Comment by dhalbert** [comment]
See https://github.com/adafruit/circuitpython/issues/7366#issuecomment-1359928263
