### ISSUE TITLE
use logger with NullHandler by default

### ISSUE THREAD

**Issue by vladak** [adafruit/Adafruit_CircuitPython_MiniMQTT#146]
There is a lot blocks in `MQTT` that go like this:
```python
    if self.logger is not None:
        self.logger.debug("Setting last will properties")
```
The check for the logger makes the code more difficult to read. Setting a logger with `NullHandler` by default and replacing the handler with `StreamHandler` in `enable_logger()` would avoid these contructs.

**Comment by tekktrik** [comment]
Sounds like a good improvement to readability!

**Comment by tekktrik** [comment]
Do you want to submit a PR for this?

**Comment by dastels** [comment]
The whole idea of a null handler (the null object pattern in general) is so you don't have to do checks like that. Someone didn't get the memo I guess.

**Comment by vladak** [comment]
> Do you want to submit a PR for this?

Possibly, eventually. I have some other changes in the works that would merge badly with this change.
