### ISSUE TITLE
if broker is down, minmqtt behavior could be made simpler to recover

### ISSUE THREAD

**Issue by schaefer01** [adafruit/Adafruit_CircuitPython_MiniMQTT#149]
hi,
  when the broker is down, there's no clean way to access the socket to close and retry
  if the socket isn't closed, each retry grabs a new socket until there are no more sockets and
  then a no more sockets exception is raised

  I see the call .disconnect() but there is nothing to disconnect from, and the call will raise the exception, not connected.

  the socket variable needed to perform the close is self._sock

  there should either be an automatic cleanup or a call to close the socket without having to dig down into a semi-private class variable.

bob s.

**Comment by vladak** [comment]
Actually, `reconnect()` closes the socket in the process of reconnecting.

**Comment by schaefer01** [comment]
thank you
