### ISSUE TITLE
can not make mqtt_client.loop() shorter as 1 sec

### ISSUE THREAD

**Issue by MyRaspberry** [adafruit/Adafruit_CircuitPython_MiniMQTT#195]
i try:
```
ts=time.monotonic()
#mqtt_client.loop() # every second check if remote command comes in
mqtt_client.loop(timeout=0.01)
print(f"___ mqtt_client loop {(time.monotonic()-ts)} sec")
```

more see:
[test GIT of mqtt pub sub REMOTE BLINKY](https://github.com/MyRaspberry/PICO_W_MQTT_pub_sub)

**Comment by vladak** [comment]
Do you explicitly set `socket_timeout` and `recv_timeout` when initializing the `MQTT` object ?

**Comment by vladak** [comment]
Looking into the linked code this appears to be the case. This is not going to work, you need to reduce socket timeout below the loop timeout.
