### ISSUE TITLE
`free_socket` or `close_socket` ?

### ISSUE THREAD

**Issue by o-control** [adafruit/Adafruit_CircuitPython_MiniMQTT#207]
This may be due to some quirk of my code, but I've found that with this line as written:

`self._connection_manager.free_socket(self._sock)`

the MQTT connection doesn't close on calling `disconnect()`.  For me it does work if I change that line to:

`self._connection_manager.close_socket(self._sock)`

**Comment by FoamyGuy** [comment]
@justmobilize do you have any idea on this question? Are there situations where that needs to be close_socket() instead? or perhaps it should both close and free?

**Comment by o-control** [comment]
Hi

If I use the `free_socket` code then after I've called `connect` and `disconnect` once, if I then call `connect` a second time I get the message "Repeated connect failures".

Looking at what's happening in `connect`: when it's called the second time, its first connection attempt gets "No data was sent, socket was closed" from the Wiznet_5k interface. The remaining connection attempts get "Socket already connected to mqtt://xxx.xxx.xxx.xxx:1883". At that point, if I call `disconnect` I get the message "MiniMQTT is not connected".

**Comment by justmobilize** [comment]
Sounds good. Let me take a look at it.

**Comment by brentru** [comment]
>  I would imagine without calling ping the socket would disconnect and so it's just better to fully close it out.

Per the MQTT spec, without a call to `ping()` within the KEEPALIVE time, the timer will expire and the MQTT broker will disconnect the client's session.

> Would you agree?

I don't fully understand the use case on this issue

**Comment by o-control** [comment]
Thanks everyone!

**Comment by justmobilize** [comment]
@o-control thanks for opening the issue
