### ISSUE TITLE
generic timeout error when 'is_ssl' param not set for an mqtt service that requires it

### ISSUE THREAD

**Issue by jersu11** [adafruit/Adafruit_CircuitPython_MiniMQTT#214]
This was discovered while debugging [a connection issue](https://github.com/adafruit/Adafruit_CircuitPython_AWS_IOT/issues/23#issuecomment-2118250899) with the adafruit_aws_iot library. When the MQTT client is instantiated without the `is_ssl` param for a service that requires ssl, the MQTT client will attempt retries and eventually fail with an error that is perhaps too generic. 
```
MMQTTException('Repeated connect failures',)
```

**Comment by justmobilize** [comment]
investigating
