### ISSUE TITLE
After pystack limit reached, MQTT service continues retry until timeout

### ISSUE THREAD

**Issue by jersu11** [adafruit/Adafruit_CircuitPython_MiniMQTT#215]
Adafruit CircuitPython 9.0.4 on 2024-04-16; Adafruit PyPortal with samd51j20

Discovered while debugging [a connection issue](https://github.com/adafruit/Adafruit_CircuitPython_AWS_IOT/issues/23#issuecomment-2118323414) with adafruit_aws_iot library. If the `pystack` is exhausted, the MQTT client will continue retrying until eventually failing with `MMQTTException('Repeated connect failures',)`

```
1564.623: WARNING - Socket error when connecting: pystack exhausted
1564.625: DEBUG - Resetting reconnect backoff
1564.821: DEBUG - Attempting to connect to MQTT broker (attempt #0)
1564.823: DEBUG - Attempting to establish MQTT connection...
1564.827: WARNING - Socket error when connecting: Socket already connected to mqtt://asxxxxxxxxxoy-ats.iot.us-west-2.amazonaws.com:8883
1564.829: DEBUG - Resetting reconnect backoff
1564.832: DEBUG - Attempting to connect to MQTT broker (attempt #0)
1564.833: DEBUG - Attempting to establish MQTT connection...
1564.837: WARNING - Socket error when connecting: Socket already connected to mqtt://asxxxxxxxxxoy-ats.iot.us-west-2.amazonaws.com:8883
1565.035: DEBUG - Resetting reconnect backoff
1565.037: DEBUG - Attempting to connect to MQTT broker (attempt #0)
1565.039: DEBUG - Attempting to establish MQTT connection...
1565.042: WARNING - Socket error when connecting: Socket already connected to mqtt://asxxxxxxxxxoy-ats.iot.us-west-2.amazonaws.com:8883
1565.044: DEBUG - Resetting reconnect backoff
1565.047: DEBUG - Attempting to connect to MQTT broker (attempt #0)
1565.048: DEBUG - Attempting to establish MQTT connection...
1565.247: WARNING - Socket error when connecting: Socket already connected to mqtt://asxxxxxxxxxoy-ats.iot.us-west-2.amazonaws.com:8883
Traceback (most recent call last):
  File "code.py", line 159, in <module>
  File "adafruit_aws_iot.py", line 145, in connect
AWS_IOT_ERROR: ('Error connecting to AWS IoT: ', MMQTTException('Repeated connect failures',))
```

**Comment by justmobilize** [comment]
investigating

**Comment by chrisgilldc** [comment]
Updated to CP 9.0.4 and am having  similar behavior. Client gets stuck in a PINGREQ loop and never gets out, even once the broker is back up.

**Comment by dhalbert** [comment]
@chrisgilldc Please say which board you are using and have you updated to the latest version of all the libraries?

**Comment by chrisgilldc** [comment]
@dhalbert This is on a Metro M4 Airlift Lite. Libraries were updated to the latest from the bundle. I'm out at the moment but can try updating the libraries individually later today.

**Comment by justmobilize** [comment]
Also, have you updated your airlift firmware?

**Comment by justmobilize** [comment]
@chrisgilldc I might also recommend this branch: https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/pull/213 as it has a little better error logging
