### ISSUE TITLE
lines 216 and 220 both modify the broker string, thus not allowing reconnect to work

### ISSUE THREAD

**Issue by bangell** [adafruit/Adafruit_CircuitPython_MiniMQTT#26]
proto, dummy, self.broker = self.broker.split("/", 2)

self.broker gets modified during connect, however if you do a reconnect, it tries to parse broker again, however broker was already parsed down (removed the photo, and path).  the split fails as  broker only contains the host address and there are not enough values to unpack.  I would have done a request for pull on this, but didn't know how you wanted to handle this situation.

my broker was set to:  http://10.0.0.16

**Comment by bangell** [comment]
try:
            proto, dummy, self.broker, path = self.broker.split("/", 3)
            # replace spaces in path
            path = path.replace(" ", "%20")
        except ValueError:
            proto, dummy, self.broker = self.broker.split("/", 2)
            path = ""

This code in connect will not work when called by reconnect because the broker string gets modified here. It fails in the except routine because broker is just the host address when called for second time so the split fails

**Comment by brentru** [comment]
@bangell  Since `self.broker` is only within `init` and `connect`, we could handle this by creating a new `broker` variable and preserving the value of the original `self.broker`:

`            proto, dummy, broker, path = self.broker.split("/", 3)`
`        proto, dummy, broker= self.broker.split("/", 2)`

**Comment by jimbobbennett** [comment]
Hey @bangell - this should be fixed in the [latest release](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/releases/tag/2.2.0). Can you test my fix please and see if it resolves this issue.

**Comment by bangell** [comment]
you bet!

**Comment by bangell** [comment]
Thanks, it worked like a champ!
