### ISSUE TITLE
The default value for the payload parameter is not supported in the will_set method 

### ISSUE THREAD

**Issue by jimbobbennett** [adafruit/Adafruit_CircuitPython_MiniMQTT#39]
To reproduce:

Call the `will_set` method and leave the `payload` parameter as its default value of `None`.

This causes an exception of `Message can not be none`.

If the payload can't be `None`, then it should not have a default value of `None` - all default values should work as their existence implies that the value is allowed.

**Comment by 2bndy5** [comment]
To be clear, are we expecting to mimic paho_mqtt behavior? In that case, a payload of `None` would be replaced with a zero-length string as described in `will_set()` of the [paho_mqtt docs](https://pypi.org/project/paho-mqtt/#option-functions).

**Comment by brentru** [comment]
@2bndy5  @jimbobbennett  Yes, I'd like to be in-like with paho mqtt as much as possible in this library.

**Comment by brentru** [comment]
fixed by https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/pull/47
