### ISSUE TITLE
MiniMQTT client timeout after successful connection with ESP_ATControl

### ISSUE THREAD

**Issue by hussnainahmed** [adafruit/Adafruit_CircuitPython_MiniMQTT#48]
I am trying to connect to mqtt broker via wifi from Particle Argon device using circuitpython minimqtt. Wifi setup was done using ESP AT Control as in this example https://github.com/adafruit/Adafruit_CircuitPython_ESP_ATcontrol/blob/master/examples/esp_atcontrol_simpletest.py.
For testing mqtt publish, I am using minimqtt simple test example https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/master/examples/minimqtt_simpletest.py

on client.connect() I can see from mosquito mqtt broker logs that client is connected. However, it times out and disconnects. Most probably because of no CONNACK.  I need help.

```
1595772303: New client connected from xxx.xxx.xxx.xxx as cpyxxx (xx, xxx, u'<user>').
1595772394: Client cpyxxx has exceeded timeout, disconnecting.
1595772394: Socket error on client cpyxxx, disconnecting.
1595772514: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
```

**Comment by brentru** [comment]
This library does check for a CONNACK from the broker (https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/master/adafruit_minimqtt/adafruit_minimqtt.py#L369).

The keep-alive in this library (https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/master/adafruit_minimqtt/adafruit_minimqtt.py#L131) is set to 60 seconds, does this match the keep-alive of your Mosquitto broker?

**Comment by hussnainahmed** [comment]
Yes, the default keep-alive for Mosquito broker is also 60 seconds. I did not change it.

**Comment by brentru** [comment]
Does the disconnection happen immediately _after_ connection, or _after_ another action (publish, subscribe)?

**Comment by hussnainahmed** [comment]
```
1595772303: New client connected from xxx.xxx.xxx.xxx as cpyxxx (xx, xxx, u'<user>').
1595772394: Client cpyxxx has exceeded timeout, disconnecting.
1595772394: Socket error on client cpyxxx, disconnecting.
1595772514: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
```
From these logs, you can see it connects then after 90 seconds (60s keep-alive + grace period ) it disconnects. No publish subcribe.

**Comment by brentru** [comment]
@jerryneedell  Have you encountered something similar to this with the Particle boards and MiniMQTT?
