### ISSUE TITLE
import failing - cannot perform relative import

### ISSUE THREAD

**Issue by codingbandit** [adafruit/Adafruit_CircuitPython_MiniMQTT#51]
I am attempting to use this library from the [CircuitPython library download, version 6](https://circuitpython.org/libraries), but as soon as I include the import (as shown in the examples), I am receiving an error "cannot perform relative import".  Line 48 of adafruit_minimqtt.py is relatively loading the matcher. 

I ultimately would like to use this library with the [Adafruit Azure IoT library](https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT), but it can't find the module (even though it's copied to lib) - the import in the IoT lib doesn't match the minimqtt examples.

I'm not familiar enough with the CircuitPython build tools for building bundles, one day I will attempt this myself - but this issue is a bit more pressing at the moment as I wish to include it in a presentation - any assistance is appreciated. Please let me know if you need anything additional, or if I totally missed the boat on something easy :)

![image](https://user-images.githubusercontent.com/3979478/99480549-4b138a80-2926-11eb-99c6-7c614a3d4b65.png)

**Comment by codingbandit** [comment]
I've worked around this issue temporarily by copying the source files, I moved the matcher class directly into the adafruit_minimqtt.py file, and in the source file in the Azure IoT library (iot_mqtt.py) changed the imports to :

import adafruit_minimqtt.adafruit_minimqtt as minimqtt
from adafruit_minimqtt.adafruit_minimqtt import MQTT

So I am functional :)

**Comment by brentru** [comment]
@codingbandit Thanks for reporting this. I'm working "in" this library this week (addressing some issues) and I'll take a look at this issue.

> I've worked around this issue temporarily by copying the source files, I moved the matcher class directly into the adafruit_minimqtt.py file

Do you mean you copy and pasted the code for the `matcher` class into MiniMQTT as a separate class?

Also - it seems this issue is also relevant to how the Azure IoT library imports in `iot_mqtt`, could you please file an issue on that repository as well? 

Thanks!

**Comment by codingbandit** [comment]
Hi @brentru - yes, I just went ahead and included the matcher class in the adafruit_minimqtt.py temporarily when I copied the files over. I didn't really test if was necessary TBH. I will file an issue with the Azure IoT library once this one gets straightened out (this way we won't be chasing each others tails :) ) - thank you so much!

**Comment by codingbandit** [comment]
@brentru - just an FYI - I don't seem to be having this issue any longer (I did a fresh download of CircuitPython and the libs and I am not getting the relative import any longer. Feel free to close this one if you would like. In the meantime, I will submit a PR into the Azure IOT with the fixed imports.

**Comment by brentru** [comment]
Ok - will be replying over on https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT/pull/23
