### ISSUE TITLE
Catch MMQTTException 

### ISSUE THREAD

**Issue by sops21** [adafruit/Adafruit_CircuitPython_MiniMQTT#59]
I'm trying to catch MMQTTException errors 
```
while True:
    try:
        # Poll the message queue
        mqtt_client.loop()
    except (ValueError, RuntimeError, MMQTTException) as e:
        print("Failed to get data, retrying\n", e)
      
        mqtt_client.reconnect()
        # continue
    time.sleep(1)
```

But then I received: 
`NameError: name 'MMQTTException' is not defined`

Is there a better way to catch the exceptions?

**Comment by brentru** [comment]
`MMQTTException ` is a class defined in `adafruit_minimqtt` so you'd need to add the following line to the top of your code.py:

`from adafruit_minimqtt.adafruit_minimqtt import MMQTTException`

**Comment by sops21** [comment]
Thanks that worked! 
Is that more correct than doing: 
`except (ValueError, RuntimeError, MQTT.MMQTTException) as e:`

Just wondering as I'm pretty new to python.

**Comment by brentru** [comment]
Assuming you imported `MQTT` using `import adafruit_minimqtt.adafruit_minimqtt as MQTT`, they're both valid..

The import statement above imports the entire module, `adafruit_minimqtt.py` which includes two classes, `MQTT` and `MMQTTException`
https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/master/adafruit_minimqtt/adafruit_minimqtt.py

By just calling `...import MMQTTException`, you import the code within the `MQTTException` class
https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/master/adafruit_minimqtt/adafruit_minimqtt.py#L67

More info about this: https://realpython.com/python-import/#packages
