### ISSUE TITLE
CPython example not working with secure broker

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_CircuitPython_MiniMQTT#62]
This library currently works with CPython sockets connecting to a insecure MQTT broker port (1883) but falls down when attempting to connect to a secure MQTT broker port (8883):

```Traceback (most recent call last):
  File "/Users/brentrubell/Desktop/github_brentru/Adafruit_CircuitPython_MiniMQTT/test_cpython.py", line 63, in <module>
    mqtt_client.connect()
  File "/Users/brentrubell/Desktop/github_brentru/Adafruit_CircuitPython_MiniMQTT/adafruit_minimqtt/adafruit_minimqtt.py", line 467, in connect
    self._sock = self._get_socket(self.broker, self.port)
  File "/Users/brentrubell/Desktop/github_brentru/Adafruit_CircuitPython_MiniMQTT/adafruit_minimqtt/adafruit_minimqtt.py", line 284, in _get_socket
    sock = self._ssl_context.wrap_socket(sock, server_hostname=host)
  File "/Users/brentrubell/Desktop/github_brentru/Adafruit_CircuitPython_MiniMQTT/adafruit_minimqtt/adafruit_minimqtt.py", line 114, in wrap_socket
    return _FakeSSLSocket(socket, self._iface.TLS_MODE)
AttributeError: 'NoneType' object has no attribute 'TLS_MODE'```

**Comment by brentru** [comment]
Digging deeper, this is more an issue with the example itself and the macOS SSL installation under Python3 than the library, I'll be making a pull request shortly to fix it.

In the future, if a user on macOS gets `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)`, they'll need to upgrade the `certifi` package by running the following command: 

`/Applications/Python\ 3.9/Install\ Certificates.command`

**Comment by tannewt** [comment]
Why are you using FakeSSLSocket when using CPython? Your self._ssl_context should be from the real `ssl` library.

**Comment by tannewt** [comment]
FakeSSLSocket should only be used with ESP32SPI.

**Comment by brentru** [comment]
@tannewt  The code which threw this error incorrectly did not pass the `ssl_context` into the MiniMQTT constructor and looked like:

```
# Set up a MiniMQTT Client
mqtt_client = MQTT.MQTT(
    broker=secrets["broker"],
    username=secrets["aio_username"],
    password=secrets["aio_key"],
    socket_pool=socket,
)
```

Instead of: 

```
# Set up a MiniMQTT Client
mqtt_client = MQTT.MQTT(
    broker=secrets["broker"],
    username=secrets["aio_username"],
    password=secrets["aio_key"],
    socket_pool=socket,
    ssl_context=ssl.create_default_context(),
)
```

**Comment by brentru** [comment]
Looking at how requests does it, we should be throwing a `RuntimeError` that the `"ssl_context must be set before using adafruit_mqtt for secure MQTT."` here https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/master/adafruit_minimqtt/adafruit_minimqtt.py#L253
