### ISSUE TITLE
Debug logger messages cause runtime error

### ISSUE THREAD

**Issue by dlizotte-uwo** [adafruit/Adafruit_CircuitPython_MiniMQTT#67]
Debug messages sent to an adafruit logger that try to format a `bytearray` with a `%x` format code crash the logger. Happens at line 513 for sure, possibly also line 637.

**Comment by brentru** [comment]
@dlizotte-uwo  I'm not sure if this is a MiniMQTT issue and not a CircuitPython-Logging issue, since the logger is passed to this library.

Does this issue still happen when you try to log a bytearray using the example in `circuitpython-logging`? https://github.com/adafruit/Adafruit_CircuitPython_Logging/blob/master/examples/logging_simpletest.py

**Comment by dlizotte-uwo** [comment]
Yes; same thing. circuitpython-logging uses the % operator to format strings; the % operator can't format a bytearray into a %x, it seems.

```
import adafruit_logging as logging

logger = logging.getLogger("test")

logger.setLevel(logging.DEBUG)
logger.info("Info message")
logger.error("Error message")
logger.error("An int: %x",127)
ba = bytearray([127,255,0])
logger.error("A bytearray: %x", ba)
```

Here is what MiniMQTT does if logging at the DEBUG level:

```
109.409: DEBUG - Attempting to establish MQTT connection...
112.462: DEBUG - Sending CONNECT to broker...
Traceback (most recent call last):
  File "code.py", line 238, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 513, in connect
  File "adafruit_logging.py", line 184, in debug
  File "adafruit_logging.py", line 175, in log
TypeError: can't convert bytearray to int
```

**Comment by brentru** [comment]
Ok, this is an issue with CircuitPython Logging, not MiniMQTT

Please file an issue over on the Logging repo: https://github.com/adafruit/Adafruit_CircuitPython_Logging/issues. Once it's fixed there, it'll be fixed here.

**Comment by dlizotte-uwo** [comment]
I think for them it would be a feature request and require a fundamental change to circuitpython to allow % to format a bytearray with %x. But I'll file an issue.
