### ISSUE TITLE
unable to connect to MQTT Broker without using SSL

### ISSUE THREAD

**Issue by bikenbruce** [adafruit/Adafruit_CircuitPython_MiniMQTT#75]
Hello-
This is my first bug reporting using github, so please correct me if you need more information.

I've been testing out the PyPortal and Matrix Portal to connect with a MQTT broker that is not using an SSL based connection.  The basic configuration that I've used is:
client = MQTT.MQTT(
    broker='SERVER NAME HERE',
    port=1883,
)

and the error that I see is:
Traceback (most recent call last):
  File "code.py", line 94, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 437, in connect
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 235, in _get_connect_socket
AttributeError: 'NoneType' object has no attribute 'info'

People have posted this error too on the forums, but I don't believe it has been folded into the code.  There's a few suggestions on how to resolve the issue.

https://forums.adafruit.com/viewtopic.php?f=60&t=176301&p=858740&hilit=mqtt+ssl#p858740

Please advise if there's anything that I should do to further help / assist with resolving this issue and contributing to this code.

I really appreciate all the wonderful work Adafruit team does for the community.  Thank you!

**Comment by ghayne** [comment]
This is more or less the same as:
https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/73

**Comment by bikenbruce** [comment]
Yes, correct.  I'm closing this issue
