### ISSUE TITLE
MemoryError because of too big bytearray

### ISSUE THREAD

**Issue by dherrada** [adafruit/Adafruit_CircuitPython_MiniMQTT#82]
https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/3c82dda7d4f03926cc0d25f75911ff2702262159/adafruit_minimqtt/adafruit_minimqtt.py#L881

The first 12 lines are normal. Then, for some reason, it stops getting the ISO8601 feed, and the time in-between runs decreases. The time has to be at least .1 seconds, but the loop timeout is .25 seconds, so it should be higher than that if it's still looking for the time value.
The numbers under 1 are the time in-between every loop run, and the very large number is the amount of memory left.

My guess at what's happening is that for whatever reason bufsize becomes so big that it would take up all the memory. I'm also running gc.collect() at the end of every loop run, so it seems the buffer gets made, getting bigger and bigger (I'm assuming that starts happening at line 13 (right after where I wrote unexpected behavior). 
```
EXPECTED BEHAVIOR
2021-06-09 15:55:57.619000-04:00
0.386719
1915456
0.386719
1915456
2021-06-09 15:55:58.619000-04:00
0.496094
1915440
0.382813
1915440
0.386719
1915440
UNEXPECTED BEHAVIOR
0.136719
1915440
0.136719
1915440
0.132813
1915440
0.140625
1915440
0.136719
1915440
0.140625
1915440
0.136719
1915440
0.136719
1915440
0.132813
1915440
0.132813
1915440
0.132813
1915440
0.136719
1915440
Traceback (most recent call last):
  File "code.py", line 278, in <module>
  File "code.py", line 245, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 786, in loop
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 835, in _wait_for_msg
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 881, in _sock_exact_recv
MemoryError: memory allocation failed, allocating 4294955011 bytes
```

**Comment by dherrada** [comment]
In case it's something I'm doing wrong, here's my code: https://gist.github.com/dherrada/cdf2e5f328900b11b9baa224137be4dd

**Comment by dherrada** [comment]
@brentru Here's the code that should be easier to reproduce with https://gist.github.com/dherrada/ea35a128a1568ed85b126c6f5cbb3506
The code is running on a Metro ESP32-S2 running CircuitPython 6.3.0

**Comment by dherrada** [comment]
@brentru Oh and btw, I was able to replicate this just using minimqtt.

**Comment by riffnshred** [comment]
I think I have the same issue. Let me know if not. 

Im on a Matrix Portal running Circuit Python 6.3.0 and Adafruit_minimqtt from the most recent library package.

Im working with the Octoprint MQTT pluging to get data from my 3d printer. At some point while the loop() run, it blocks for a good minute and then I get that same memory error but with much smaller byte array then what @dherrada is getting. 

I was able to free up some memory to see if that message would get through and this is the result I got:

this is the function I use to store the message when the topic updates and it prints the message and topic in the REPL
```
def get_message(client, topic, message):
    gc.collect()
    print("Received {} for {}".format(message, topic))
    mqtt_messages[topic] = message
```

This is what the usual statement I get.
`Received {"_timestamp": 1625319391, "actual": 23.8, "target": 0.0} for octoPrint/temperature/bed`

NOW. when the loop() function block for some reason, after a min, this is what shows up in the REPL
```
Received  for timestamp": 1625318700, "actual": 23.9, "target": 0.0}0T/octoPrint/temperature/bed{"_timestamp": 1625318700, "actual": 24.6, "target": 0.0}0VfloctoPrint/temperature/tool0{"_timestamp": 1625318705, "actual": 23.2, "target": 0.0}0T/
octoPrint/temperature/bed{"_timestamp": 1625318705, "actual": 24.6, "target": 0.0}0VfloctoPrint/temperature/tool0{"_timestamp": 1625318710, "actual": 23.2, "target": 0.0}0T.....(This goes on for multiple lines)
```

Note there is nothing in the `message` and everything is in the `topic`.
After this, the loop() block again but for 5 to 10 seconds and it get back to normal.

**Comment by riffnshred** [comment]
@dherrada have you tried using The 7.0.0 alpha version with the matching libraries? 

I installed it yesterday morning and let my code run all night since then and my problem is gone.

**Comment by dherrada** [comment]
@riffnshred Thanks for the testing. I'll try installing 7 and see if that fixes it

**Comment by riffnshred** [comment]
no problem. side note, just dragging and replacing the libraries didn work for all of them. Deleting and then copy pasting did. 

cheers

**Comment by dherrada** [comment]
Yeah, that's what I've been noticing lately.

**Comment by dherrada** [comment]
@riffnshred Yep. That fixes it. Thanks!
