### ISSUE TITLE
Seemingly no support for TLS

### ISSUE THREAD

**Issue by jatmega** [adafruit/Adafruit_CircuitPython_MiniMQTT#83]
Greetings great programmers!

Kowledge level: Copy-pasting and happy when things dont crash :)

It would be of interest for me to be able to use TLS when connecting to the MQTT broker.
I have tried, but not been able to find any way to do this. 
It might just be some obvious way to do this, which I just have not found.

There is an example under the ESPSPI-folder, with credentials, but it did not make me much smarter.

Thanks for all the good programming you guys do!

**Comment by ladyada** [comment]
tls is handled at a lower abstraction later, it isnt part of mqtt - if your broker has tls available on a port, just use that port. if you need help with circuitpython projects please use discord
