### ISSUE TITLE
Incorrect type in docstring for second argument of MQTT.add_topic_callback(..)

### ISSUE THREAD

**Issue by garrettheath4** [adafruit/Adafruit_CircuitPython_MiniMQTT#88]
The method signature of `MQTT.add_topic_callback(..)` on [line 367 of adafruit_minimqtt.py](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/62d1921ae674c8cd67a026d18da6305355085946/adafruit_minimqtt/adafruit_minimqtt.py#L367) is:

```
    def add_topic_callback(self, mqtt_topic, callback_method):
        """Registers a callback_method for a specific MQTT topic.
        :param str mqtt_topic: MQTT topic identifier.
        :param str callback_method: Name of callback method.
        """
```

As you can see, the docstring indicates that both method arguments are strings. I believe this is an error though. Shouldn't the second argument `callback_method` be a _method_ instead of a string?

**Comment by brentru** [comment]
Correct, it should be a method. Could you submit a Pull Request fixing this?

**Comment by garrettheath4** [comment]
Created PR #89. Sorry I should have just done that from the beginning, lol.
